[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xBC100D"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x1E2220"
foreground = "0xffffff"

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "cica"
style = "Bold"

[font.bold_italic]
family = "cica"
style = "Bold Itali"

[font.italic]
family = "cica"
style = "Italic"

[font.normal]
family = "cica"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 0.9

[window.padding]
x = 1
y = 0
